### ISSUE TITLE
没有app.json ,打不开

### ISSUE THREAD

**Issue by JackyXXX** [zprial/wx-book#1]
没有app.json ,打不开

**Comment by zprial** [comment]
> 没有app.json ,打不开

需要`npm run build`

**Comment by JackyXXX** [comment]
在目录里运行cmd，再输入npm start和npm run build都有报错，能不能具体教一下怎么使用？谢谢！

**Comment by zprial** [comment]
> 在目录里运行cmd，再输入npm start和npm run build都有报错，能不能具体教一下怎么使用？谢谢！

有`npm install` 或者 `yarn install` 吗，还不行的话把错误日志贴一下吧

**Comment by JackyXXX** [comment]
![image](https://user-images.githubusercontent.com/48507593/55772064-353cb300-5abd-11e9-8db4-598d119b45ce.png)

**Comment by zprial** [comment]
我这边没有windows的电脑，没出现这种情况，你试下用管理员权限打开cmd，推荐用powershell或者git bash
