### ISSUE TITLE
不知道能否私发一份带接口的么。

### ISSUE THREAD

**Issue by keventseng** [zprial/wx-book#2]
不知道能否私发一份带接口的么。：P

**Comment by zprial** [comment]
> 不知道能否私发一份带接口的么。：P

postman link: https://www.getpostman.com/collections/62164b16f39f10332047

**Comment by keventseng** [comment]
npm install 正常了，但是在构建的时候，一直报错。：（

**Comment by keventseng** [comment]
> wx-book@0.1.0 build /Users/zengguanlin/Downloads/wx-book-master
> node build/build.js

Hash: 0c30de489e79a06a3488
Version: webpack 3.12.0
Time: 2236ms
                          Asset       Size  Chunks             Chunk Names
 static/js/pages/source/main.js  400 bytes       0  [emitted]  pages/source/main
 static/js/pages/search/main.js  402 bytes       1  [emitted]  pages/search/main
  static/js/pages/index/main.js  400 bytes       2  [emitted]  pages/index/main
static/js/pages/history/main.js  400 bytes       3  [emitted]  pages/history/main
static/js/pages/details/main.js  400 bytes       4  [emitted]  pages/details/main
static/js/pages/chapter/main.js  400 bytes       5  [emitted]  pages/chapter/main
               static/js/app.js  400 bytes       6  [emitted]  app
          static/js/manifest.js  860 bytes       7  [emitted]  manifest

ERROR in ./src/pages/index/main.js
Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
    at Object.module.exports (/Users/zengguanlin/Downloads/wx-book-master/node_modules/mpvue-loader/lib/loader.js:55:11)

ERROR in ./src/pages/details/main.js
Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
    at Object.module.exports (/Users/zengguanlin/Downloads/wx-book-master/node_modules/mpvue-loader/lib/loader.js:55:11)

ERROR in ./src/main.js
Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
    at Object.module.exports (/Users/zengguanlin/Downloads/wx-book-master/node_modules/mpvue-loader/lib/loader.js:55:11)

ERROR in ./src/pages/history/main.js
Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
    at Object.module.exports (/Users/zengguanlin/Downloads/wx-book-master/node_modules/mpvue-loader/lib/loader.js:55:11)

ERROR in ./src/pages/search/main.js
Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
    at Object.module.exports (/Users/zengguanlin/Downloads/wx-book-master/node_modules/mpvue-loader/lib/loader.js:55:11)

ERROR in ./src/pages/chapter/main.js
Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
    at Object.module.exports (/Users/zengguanlin/Downloads/wx-book-master/node_modules/mpvue-loader/lib/loader.js:55:11)

ERROR in ./src/pages/source/main.js
Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
    at Object.module.exports (/Users/zengguanlin/Downloads/wx-book-master/node_modules/mpvue-loader/lib/loader.js:55:11)

  Build failed with errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wx-book@0.1.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wx-book@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zengguanlin/.npm/_logs/2019-04-10T13_17_51_044Z-debug.log

**Comment by zprial** [comment]
重新pull下，8个月前的代码了，mpvue有不兼容的更新，锁了下版本
