### ISSUE TITLE
打包app

### ISSUE THREAD

**Issue by liuanyin** [zprial/wx-book#4]
请问这个项目可以直接打包android的app吗？

**Comment by zprial** [comment]
> 请问这个项目可以直接打包android的app吗？

并不行，这个只是小程序

**Comment by wga199** [comment]
请问下build打包后，在小程序中能正常运行，但是start后，没有显示路径啊？看不到界面吗？

**Comment by wga199** [comment]
然后我在dev-server.js中找到地址了，但是打开后显示的是Cannot GET /

**Comment by wga199** [comment]
哈哈哈，对不起了，昨天太晚没有去看mpvue的框架，今天去看了下，mpvue是这么开发的
